import raw from './data/marketplace.json';

export interface Skill {
  name: string;
  description: string;
  /** Omitted when the frontmatter has no `argument-hint`. */
  argumentHint?: string;
  /** Namespaced slash command. Omitted when the skill is model-loaded only. */
  command?: string;
}

export interface Agent {
  name: string;
  description: string;
}

export interface Plugin {
  name: string;
  displayName: string;
  version: string;
  category: string;
  /** One-breath pitch from the catalog entry. */
  summary: string;
  homepage: string;
  installCommand: string;
  hookEvents: string[];
  skills: Skill[];
  agents: Agent[];
}

export interface Site {
  name: string;
  /** Read by vite.config.mts for the meta tags, not by the page body. */
  description: string;
  repo: string;
  repoUrl: string;
  addCommand: string;
  categories: string[];
  totals: { plugins: number; skills: number; agents: number };
  plugins: Plugin[];
}

// Generated by scripts/build-site-data.mjs; the shape is asserted in its test.
export const site = raw as Site;

/** Word only — pluralized when count is not one. Used where the count is shown separately. */
export const pluralWord = (count: number, word: string) => `${word}${count === 1 ? '' : 's'}`;

export const plural = (count: number, word: string) => `${count} ${pluralWord(count, word)}`;
