import raw from './data/marketplace.json';

export interface Skill {
  name: string;
  description: string;
  argumentHint: string | null;
  invocable: boolean;
  /** Namespaced slash command, or null when the skill is model-loaded only. */
  command: string | null;
}

export interface Agent {
  name: string;
  description: string;
}

export interface Plugin {
  name: string;
  displayName: string;
  version: string;
  category: string;
  /** One-breath pitch from the catalog entry. */
  summary: string;
  /** Long form from the plugin manifest. */
  description: string;
  keywords: string[];
  homepage: string;
  installCommand: string;
  hookEvents: string[];
  skills: Skill[];
  agents: Agent[];
}

export interface Site {
  name: string;
  description: string;
  owner: string;
  repo: string;
  repoUrl: string;
  addCommand: string;
  categories: string[];
  totals: { plugins: number; skills: number; commands: number; agents: number };
  plugins: Plugin[];
}

// Generated by scripts/build-site-data.mjs; the shape is asserted in its test.
export const site = raw as Site;
